spring:
  application:
    name: marketPlace
  security:
    oauth2:
      resourceserver:
        jwt:
          issuer-uri: http://mysqldb:8085/realms/my-realm
  datasource:
    url: jdbc:mysql://mysqldb:3306/hassan?useSSL=false&allowPublicKeyRetrieval=true
    username: developer
    password: ENC(6xGtbNDwxNUW9O8TeWT+Mx4NPX947sE1)
    driver-class-name: com.mysql.cj.jdbc.Driver

  jpa:
    hibernate:
      ddl-auto: update
    database-platform: org.hibernate.dialect.MySQLDialect

jakarta:
  persistence:
    jdbc:
      url: jdbc:mysql://localhost:3306/hassan
server:
  servlet:
    context-path: /marketPlace
  port: 8090


keycloak:
  realm: my-realm
  clientId: marketPlace
  rootClient: adminKeycloack
  serverUrl: http://localhost:8085
  clientSecret: x2ZG0eO4lkcMNJQjzJTFHNr3I7nxJP86

# \u062A\u0646\u0638\u06CC\u0645\u0627\u062A \u0627\u0635\u0644\u06CC Jasypt

jasypt:
  encryptor:
    password: mySecretKey123
    algorithm: PBEWithMD5AndDES
    iv-generator-classname: org.jasypt.iv.NoIvGenerator
